global:
  runner:
    os_image: ubuntu
  tasks:
    unit-tests:
      steps: 
      - checkout # clone the git repo - reports/html:
        dir: coverage
        index: index.html
   compile:
     steps:
     # clone git repo
     - checkout
     - publish:
          depends: [unit-tests, compile]
   deloy:
      depends: [publish]
   
