version: 2
tasks:
  build:
    steps:
      - checkout
      - commands:
        - apt-get update && apt-get install -y awscli  # Install AWS CLI
        - export AWS_ENV=production
        - aws build  # Command to build AWS website
        - aws s3 sync static-pages-folder s3://$AWS_S3_BUCKET  # Upload static pages to S3 bucket
        if: branch == 'new'

environments:
  default:
    - runner:
        os_image: ubuntu
